### ISSUE TITLE
POCustomTabAuthorizationActivity is stuck in redirect loop if the activity is being destroyed.

### ISSUE THREAD

**Issue by Tyomnuy** [processout/processout-android#111]
Hello team! 

This issue happens in the latest SDK `4.7.0` with CustomTabs enabled. 
I'm testing web payments with `POAlternativePaymentMethodCustomTabLauncher` and the `Don't Keep Activities` debug option enabled. Once payment is authorized and `POCustomTabAuthorizationActivity` is opened back by a redirect link, it launches the payment web page again. 

It happens because `CustomTabAuthorizationViewModel` is recreated, doesn't restore its state (`Launched`), and uses "CustomTabAuthorizationUiState.Initial" instead. Which launches the URI again: 
```
if (uiState == Initial) {
            _uiState.value = Launching(configuration.uri)
            return
        }
```

**Comment by vitalii-vanziak-cko** [comment]
Hey @Tyomnuy, thanks for the details.
Fixed in [4.8.1](https://github.com/processout/processout-android/releases/tag/4.8.1).
